name: Release
on:
  milestone:
    types: [closed]

env:
  POSTGIS_VERSION: 3.6.2

jobs:
  linux-amd64:
    name: Linux amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          echo "POSTGRES_VERSION=${MILESTONE_VERSION%.*}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MILESTONE_VERSION%.*}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Build Bundle
        run: ./gradlew :debian-platforms:buildAmd64DebianBundle -Pversion=$RELEASE_VERSION -PpgVersion=$POSTGRES_VERSION -PpostgisVersion=$POSTGIS_VERSION
      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: amd64DebianBundle
          path: debian-platforms/build/tmp/buildAmd64DebianBundle/bundle/postgres-linux-debian.txz

  linux-arm64:
    name: Linux arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          echo "POSTGRES_VERSION=${MILESTONE_VERSION%.*}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MILESTONE_VERSION%.*}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Build Bundle
        run: ./gradlew :debian-platforms:buildArm64v8DebianBundle -Pversion=$RELEASE_VERSION -PpgVersion=$POSTGRES_VERSION -PpostgisVersion=$POSTGIS_VERSION
      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: arm64v8DebianBundle
          path: debian-platforms/build/tmp/buildArm64v8DebianBundle/bundle/postgres-linux-debian.txz

  alpine-amd64:
    name: Alpine amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          echo "POSTGRES_VERSION=${MILESTONE_VERSION%.*}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MILESTONE_VERSION%.*}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Build Bundle
        run: ./gradlew :alpine-platforms:buildAmd64AlpineBundle -Pversion=$RELEASE_VERSION -PpgVersion=$POSTGRES_VERSION -PpostgisVersion=$POSTGIS_VERSION
      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: amd64AlpineBundle
          path: alpine-platforms/build/tmp/buildAmd64AlpineBundle/bundle/postgres-linux-alpine_linux.txz

  alpine-arm64:
    name: Alpine arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          echo "POSTGRES_VERSION=${MILESTONE_VERSION%.*}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MILESTONE_VERSION%.*}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Build Bundle
        run: ./gradlew :alpine-platforms:buildArm64v8AlpineBundle -Pversion=$RELEASE_VERSION -PpgVersion=$POSTGRES_VERSION -PpostgisVersion=$POSTGIS_VERSION
      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: arm64v8AlpineBundle
          path: alpine-platforms/build/tmp/buildArm64v8AlpineBundle/bundle/postgres-linux-alpine_linux.txz

  publish-platforms:
    name: Publish platform artifacts for ${{ github.event.milestone.title }}
    needs: [linux-amd64, linux-arm64, alpine-amd64, alpine-arm64]
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          echo "POSTGRES_VERSION=${MILESTONE_VERSION%.*}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MILESTONE_VERSION%.*}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Download bundle - amd64Debian
        uses: actions/download-artifact@v4
        with:
          name: amd64DebianBundle
          path: debian-platforms/build/tmp/buildAmd64DebianBundle/bundle
      - name: Download bundle - arm64v8Debian
        uses: actions/download-artifact@v4
        with:
          name: arm64v8DebianBundle
          path: debian-platforms/build/tmp/buildArm64v8DebianBundle/bundle
      - name: Download bundle - amd64Alpine
        uses: actions/download-artifact@v4
        with:
          name: amd64AlpineBundle
          path: alpine-platforms/build/tmp/buildAmd64AlpineBundle/bundle
      - name: Download bundle - arm64v8Alpine
        uses: actions/download-artifact@v4
        with:
          name: arm64v8AlpineBundle
          path: alpine-platforms/build/tmp/buildArm64v8AlpineBundle/bundle
      - name: Publish platform artifacts
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_CERT }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASS }}
        run: |
          ./gradlew \
            :debian-platforms:publishAmd64DebianPublicationToMavenRepository \
            :debian-platforms:publishArm64v8DebianPublicationToMavenRepository \
            :alpine-platforms:publishAmd64AlpinePublicationToMavenRepository \
            :alpine-platforms:publishArm64v8AlpinePublicationToMavenRepository \
            --info \
            -x buildAmd64DebianBundle \
            -x buildArm64v8DebianBundle \
            -x buildAmd64AlpineBundle \
            -x buildArm64v8AlpineBundle \
            -Possrh.username=$MAVEN_USER \
            -Possrh.password=$MAVEN_PASS \
            -Pversion=$RELEASE_VERSION \
            -PpgVersion=$POSTGRES_VERSION \
            -PpostgisVersion=$POSTGIS_VERSION

  publish-windows-amd64:
    name: Publish Windows amd64 for ${{ github.event.milestone.title }}
    needs: [publish-platforms]
    if: ${{ !failure() }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set environment variables
        shell: bash
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          POSTGRES_VERSION=${MILESTONE_VERSION%.*}
          echo "POSTGRES_VERSION=$POSTGRES_VERSION" >> $GITHUB_ENV
          echo "POSTGRES_BIN_VERSION=${POSTGRES_VERSION}-1" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${POSTGRES_VERSION}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Test PostgreSQL/PostGIS bundle
        shell: bash
        run: |
          ./gradlew :custom-windows-platform:testCustomWindowsJar \
            -Pversion=$RELEASE_VERSION \
            -PpgVersion=$POSTGRES_VERSION \
            -PpgBinVersion=$POSTGRES_BIN_VERSION \
            -PpostgisVersion=$POSTGIS_VERSION \
            -PdistName=windows \
            -ParchName=amd64
      - name: Publish Windows artifact
        shell: bash
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_CERT }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASS }}
        run: |
          ./gradlew :custom-windows-platform:publish --info \
            -Pversion=$RELEASE_VERSION \
            -PpgVersion=$POSTGRES_VERSION \
            -PpgBinVersion=$POSTGRES_BIN_VERSION \
            -PpostgisVersion=$POSTGIS_VERSION \
            -PdistName=windows \
            -ParchName=amd64 \
            -Possrh.username=$MAVEN_USER \
            -Possrh.password=$MAVEN_PASS

  publish-macos-arm64:
    name: Publish macOS arm64 for ${{ github.event.milestone.title }}
    needs: [publish-windows-amd64]
    if: ${{ !failure() }}
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Install psql executables
        run: |
          brew update
          brew install postgresql
          echo "$(brew --prefix postgresql)/bin" >> $GITHUB_PATH
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          POSTGRES_VERSION=${MILESTONE_VERSION%.*}
          echo "POSTGRES_VERSION=$POSTGRES_VERSION" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${POSTGRES_VERSION}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Test PostgreSQL/PostGIS bundle
        run: |
          ./gradlew :custom-darwin-platform:testCustomDarwinJar \
            -Pversion=$RELEASE_VERSION \
            -PpgVersion=$POSTGRES_VERSION \
            -PpostgisVersion=$POSTGIS_VERSION \
            -PdistName=darwin \
            -ParchName=arm64v8
      - name: Publish macOS artifact
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_CERT }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASS }}
        run: |
          ./gradlew :custom-darwin-platform:publish --info \
            -Pversion=$RELEASE_VERSION \
            -PpgVersion=$POSTGRES_VERSION \
            -PpostgisVersion=$POSTGIS_VERSION \
            -PdistName=darwin \
            -ParchName=arm64v8 \
            -Possrh.username=$MAVEN_USER \
            -Possrh.password=$MAVEN_PASS

  publish-bom:
    name: Publish BOM for ${{ github.event.milestone.title }}
    needs: [publish-macos-arm64]
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          echo "POSTGRES_VERSION=${MILESTONE_VERSION%.*}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MILESTONE_VERSION%.*}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Publish BOM
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_CERT }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASS }}
        run: |
          BOM_ARTIFACT_NAMES=embedded-postgres-binaries-linux-amd64,embedded-postgres-binaries-linux-arm64v8,embedded-postgres-binaries-linux-amd64-alpine,embedded-postgres-binaries-linux-arm64v8-alpine,embedded-postgres-binaries-windows-amd64,embedded-postgres-binaries-darwin-arm64v8
          ./gradlew publishBomPublicationToMavenRepository --info \
            -PbomArtifactNames=$BOM_ARTIFACT_NAMES \
            -Pversion=$RELEASE_VERSION \
            -PpgVersion=$POSTGRES_VERSION \
            -PpostgisVersion=$POSTGIS_VERSION \
            -Possrh.username=$MAVEN_USER \
            -Possrh.password=$MAVEN_PASS

  release:
    name: Finalize Release ${{ github.event.milestone.title }}
    needs: [publish-bom]
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up Git
        run: |
          git config user.name "Zonky Bot"
          git config user.email "bot@zonky.com"
      - name: Set environment variables
        env:
          MILESTONE_VERSION: ${{ github.event.milestone.title }}
        run: |
          echo "POSTGRES_VERSION=${MILESTONE_VERSION%.*}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MILESTONE_VERSION%.*}-$POSTGIS_VERSION" >> $GITHUB_ENV
      - name: Upload staged artifacts to Central Sonatype
        env:
          SONATYPE_USERNAME: ${{ secrets.MAVEN_USER }}
          SONATYPE_PASSWORD: ${{ secrets.MAVEN_PASS }}
        run: |
          SONATYPE_TOKEN=$(printf "$SONATYPE_USERNAME:$SONATYPE_PASSWORD" | base64)
          PUBLISH_NAMESPACE="io.zonky"
          echo "Uploading artifacts from OSSRH-Staging to Central Sonatype..."
          RESPONSE=$(curl -s -w "%{http_code}" -o response_body.txt -X POST \
            -H "Authorization: Bearer $SONATYPE_TOKEN" \
            "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/$PUBLISH_NAMESPACE?publishing_type=user_managed")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Failed to upload artifacts to Central Sonatype. Response code: $RESPONSE. Response body: "
            cat response_body.txt
            echo "Visit https://central.sonatype.com/publishing/deployments for more information."
            exit 1
          else
            echo "Artifacts were uploaded successfully to Central Sonatype."
            echo "Visit https://central.sonatype.com/publishing/deployments to view your artifacts."
          fi
      - name: Create tag
        env:
          GIT_COMMITTER_DATE: ${{ github.event.milestone.created_at }}
        run: |
          git tag -a v$RELEASE_VERSION -m "PostgreSQL $POSTGRES_VERSION"
          git push -f origin v$RELEASE_VERSION
